In [ ]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [1]:
import torch

In [2]:
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

In [3]:
print(device)

cuda


In [4]:
x = torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [5]:
x = torch.zeros(3,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
x = torch.rand(3,2)
print(x)

tensor([[0.1734, 0.1352],
        [0.7218, 0.8289],
        [0.3063, 0.2680]])


In [7]:
x = torch.empty(3,2)
print(x)

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]])


In [8]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [9]:
x = torch.linspace(0,10,5)
print(x)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [10]:
x.size()

torch.Size([5])

In [14]:
x = torch.rand(3,2)
print(x.size())

torch.Size([3, 2])

In [15]:
x.view(2,3)

tensor([[0.7473, 0.3719, 0.2334],
        [0.5846, 0.3994, 0.2023]])

In [16]:
print(x[:,1])

tensor([0.3719, 0.5846, 0.2023])

x[1,1].item()

In [19]:
print(x[1,1].item())

0.5846273303031921

In [22]:
x = torch.rand(3,2)
y = torch.rand(3,2)

In [23]:
print(x+y)

tensor([[0.1052, 1.2537],
        [0.8911, 1.1213],
        [0.9078, 1.7254]])

In [24]:
print(x*y)

tensor([[0.0012, 0.2547],
        [0.1831, 0.1559],
        [0.0157, 0.7336]])

In [25]:
print(x.matmul(y.T))

tensor([[0.2559, 0.2151, 0.7599],
        [0.2487, 0.3390, 0.7337],
        [0.2579, 0.6644, 0.7493]])

In [3]:
import numpy as np

In [28]:
x = np.array([[2,3,4],[5,6,7]])
print(x) # Numpy array

[[2 3 4]
 [5 6 7]]


In [29]:
t = torch.from_numpy(x)
print(t) # converted to tensor

tensor([[2, 3, 4],
        [5, 6, 7]])


In [5]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [4]:
torch.rand(3,2)*torch.rand(3,2)

tensor([[0.6719, 0.3123],
        [0.6250, 0.0229],
        [0.0907, 0.0453]])

In [4]:
x = torch.rand(3,2,device = "cuda")

In [6]:
print(x)

tensor([[0.9215, 0.0140],
        [0.8412, 0.6905],
        [0.5436, 0.9799]], device='cuda:0')


In [7]:
%%time
for i in range(1000):
  x = torch.randn(1000,1000)
  y = torch.randn(1000,1000)
  z = x*y

CPU times: user 15.6 s, sys: 826 ms, total: 16.4 s
Wall time: 16.4 s


In [2]:
## Auto Differentiation
x = torch.ones(3,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x+5

In [4]:
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [5]:
z = y*y + 3
print(z)

tensor([[39., 39.],
        [39., 39.],
        [39., 39.]], grad_fn=<AddBackward0>)


In [6]:
t = torch.sum(z)
print(t)

tensor(234., grad_fn=<SumBackward0>)


In [7]:
t.backward()
x.grad

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])

In [2]:
w = torch.rand(1,4, device = "cuda").normal_(mean=0,std=1)
print(w)

tensor([[ 1.7745,  0.0680, -0.9974, -0.3775]], device='cuda:0')


In [3]:
b = torch.ones(size = (1,4))
print(b)

tensor([[1., 1., 1., 1.]])


In [4]:
inp_mat = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(inp_mat)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
