In [ ]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [1]:
import torch
import numpy as np
import torch.nn as nn
from torch.nn import functional as F

In [2]:
def model(x):
  return x @ weights.t() + bias  ## @ for matrix multiplication

In [3]:
def loss(y_hat,y):
  diff = y_hat - y
  return torch.sum(diff * diff) / diff.numel()

In [4]:
factors = torch.tensor([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]],dtype=torch.float32)

fruits_traget = torch.tensor([[56,70],
                       [81,101],
                       [119,133],
                       [22,37],
                       [103,119]],dtype=torch.float32)

In [5]:
weights = torch.randn(2,3,requires_grad=True)
bias = torch.randn(2,requires_grad=True)
y_hat = model(factors)  ## y_hat is the prediction
loss1 = loss(y_hat,fruits_traget) # loss is calculated
print(loss1)

tensor(38897.3203, grad_fn=<DivBackward0>)


In [6]:
learning_rate = 0.0001
loss1.backward()
with torch.no_grad():
  weights -= weights.grad * learning_rate
  bias -= bias.grad * learning_rate
  weights.grad.zero_()
  bias.grad.zero_()

In [7]:
weights

tensor([[ 0.0040,  0.8938, -0.9331],
        [ 0.8325,  2.1783,  0.8494]], requires_grad=True)

In [8]:
y_hat1 = model(factors)  ## y_hat is the prediction
loss2 = loss(y_hat1,fruits_traget) # loss is calculated
print(loss2)

tensor(24402.0059, grad_fn=<DivBackward0>)


### For dealing with large  dataset were batches are required

In [48]:
input = factors.repeat(3,1)
target = fruits_traget.repeat(3,1)

In [49]:
input

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [22]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [24]:
train_ds = TensorDataset(input, target)
print(train_ds[0:3])

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]]))


In [26]:
train_dataloder = DataLoader(train_ds , batch_size = 5, shuffle = True)

In [29]:
print(train_dataloder)  # Stores an object at given address

In [31]:
for x, y in train_dataloder:
  print(f"input is : {x} and target is : {y}")

input is : tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]]) and target is : tensor([[ 81., 101.],
        [103., 119.],
        [119., 133.],
        [ 56.,  70.],
        [ 22.,  37.]])
input is : tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]]) and target is : tensor([[ 22.,  37.],
        [119., 133.],
        [ 81., 101.],
        [119., 133.],
        [ 56.,  70.]])
input is : tensor([[ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]]) and target is : tensor([[103., 119.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.]])


In [51]:
model = nn.Linear(3,2)
print(f"weights of model are {model.weight}")
print(f"Bias of model are {model.bias}")

weights of model are Parameter containing:
tensor([[-0.3746, -0.2403,  0.0667],
        [-0.1765,  0.3959, -0.2049]], requires_grad=True)
Bias of model are Parameter containing:
tensor([0.2396, 0.5108], requires_grad=True)


another way of checking weights and bias

In [52]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3746, -0.2403,  0.0667],
         [-0.1765,  0.3959, -0.2049]], requires_grad=True),
 Parameter containing:
 tensor([0.2396, 0.5108], requires_grad=True)]

In [53]:
# Genearate predictions
preds = model(input)
preds(preds)

tensor([[-40.3434,   5.3389],
        [-50.7333,   6.1725],
        [-60.6910,  26.3204],
        [-45.8395,  -8.0535],
        [-44.0140,  11.9944],
        [-40.3434,   5.3389],
        [-50.7333,   6.1725],
        [-60.6910,  26.3204],
        [-45.8395,  -8.0535],
        [-44.0140,  11.9944],
        [-40.3434,   5.3389],
        [-50.7333,   6.1725],
        [-60.6910,  26.3204],
        [-45.8395,  -8.0535],
        [-44.0140,  11.9944]], grad_fn=<AddmmBackward0>)

In [56]:
loss = F.mse_loss(model(input), target)
print(loss)

tensor(12317.3740, grad_fn=<MseLossBackward0>)


In [58]:
# Defining optimizer
opt = torch.optim.SGD(model.parameters(), lr = 0.00001)

In [62]:
# Defining Function for fit the data and updating weights
def fit(epoch, model, loss_fn, opt, train_dl):
  for epoch in range(epoch):
    for x, y in train_dl:
      loss = loss_fn(model(x), y)
      opt.zero_grad()
      loss.backward()
      opt.step()

    if (epoch+1) % 10 == 0:
      print(f"Epoch [{epoch+1}/{epoch}], Loss: {loss.item():.4f}")

In [64]:
fit(100, model, F.mse_loss, opt, train_dataloder)

Epoch [10/9], Loss: 237.3162
Epoch [20/19], Loss: 213.0553
Epoch [30/29], Loss: 114.6593
Epoch [40/39], Loss: 111.3890
Epoch [50/49], Loss: 93.7857
Epoch [60/59], Loss: 55.0885
Epoch [70/69], Loss: 36.9602
Epoch [80/79], Loss: 42.7515
Epoch [90/89], Loss: 32.4340
Epoch [100/99], Loss: 39.9923


In [71]:
preds = model(input)
print(preds , target)

tensor([[ 58.2220,  71.3395],
        [ 81.9734,  96.2669],
        [117.6481, 140.6428],
        [ 26.7957,  42.5269],
        [ 98.2186, 108.4114],
        [ 58.2220,  71.3395],
        [ 81.9734,  96.2669],
        [117.6481, 140.6428],
        [ 26.7957,  42.5269],
        [ 98.2186, 108.4114],
        [ 58.2220,  71.3395],
        [ 81.9734,  96.2669],
        [117.6481, 140.6428],
        [ 26.7957,  42.5269],
        [ 98.2186, 108.4114]], grad_fn=<AddmmBackward0>) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


tensor([[ 58.2220,  71.3395],
        [ 81.9734,  96.2669],
        [117.6481, 140.6428],
        [ 26.7957,  42.5269],
        [ 98.2186, 108.4114],
        [ 58.2220,  71.3395],
        [ 81.9734,  96.2669],
        [117.6481, 140.6428],
        [ 26.7957,  42.5269],
        [ 98.2186, 108.4114],
        [ 58.2220,  71.3395],
        [ 81.9734,  96.2669],
        [117.6481, 140.6428],
        [ 26.7957,  42.5269],
        [ 98.2186, 108.4114]], grad_fn=<AddmmBackward0>) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
