In [ ]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
import numpy as np
import torch

#### *Defining Activation function*

In [ ]:
def sigmoid_scaler(x):
  return 1/(1+np.exp(-x))
sigmoid  = np.vectorize(sigmoid_scaler)    # np.vectorize() --->  to convert matrix into array

def softmax(x):
  return np.exp(x)/np.exp(x).sum()

def log_loss(y,y_hat):
  return -np.sum(y*np.log(y_hat) + (1-y)*np.log(1-y_hat))

def l2_norm(y,y_hat):
  return np.sum((y-y_hat)**2)

### Softmax Function
$$\frac{e^{x_1}}{e^{x_1}+e^{x_2}+...+e^{x_3}}$$
### Sigmoid Function
$$\frac{1}{1+e^{-x}}$$


#### *Feed-forword input layer*

In [ ]:
weight1 = np.array([[.1,.3,.8,-.4],[-.3,-.2,.5,.5],[-.3,0,.5,.4],[.2,.5,-.9,.7]])
X = np.array([2,5,3,3])
bias1 = np.zeros(4)
a1 = np.matmul(weight1,X) + bias1
h1 = sigmoid(a1)
print(h1.round(2))

[0.95 0.8  0.89 0.91]


#### *Feed-forword hidden layer*

In [ ]:
weight2 = np.array([[.5,.8,.2,.4],[.5,.2,.3,-.5]])
bias2 = np.zeros(2)
a2 =  np.matmul(weight2,h1) + bias2
h2 = softmax(a2)
print(h2.round(2))

[0.77 0.23]


#### *Calculating Loss using LogLoss Function

In [ ]:
y = np.array([1,0])
loss_logloss = log_loss(y,h2)
loss_l2norm = l2_norm(y,h2)
print("Log Loss ",loss_logloss.round(2))
print("L2 norm  ",loss_l2norm.round(2))

Log Loss  0.52
L2 norm   0.11


In [ ]:
# #### *Backpropogation for Hidden layer*
d_l2norm = 2*(h2-y)
d_softmax = np.diag(h2) - np.outer(h2,h2)
d_a2 = np.matmul(d_softmax,d_l2norm)
d_w2 = np.outer(d_a2,h1)
d_b2 = d_a2
d_h1 = np.matmul(weight2.T,d_a2)

# #### *Backpropogation for Input layer*
d_sigmoid = h1*(1-h1)
d_a1 = d_h1*d_sigmoid
d_w1 = np.outer(d_a1,X)
d_b1 = d_a1

# #### *Updating Weights and Biases*
learning_rate = 0.1
weight1 = weight1 - learning_rate*d_w1
weight2 = weight2 - learning_rate*d_w2
bias1 = bias1 - learning_rate*d_b1
bias2 = bias2 - learning_rate*d_b2

print("Updated Weights for Input Layer:\n", weight1.round(2))
print("Updated Weights for Hidden Layer:\n", weight2.round(2))
print("Updated Biases for Input Layer:\n", bias1.round(2))
print("Updated Biases for Hidden Layer:\n", bias2.round(2))


Updated Weights for Input Layer:
 [[ 0.1   0.3   0.8  -0.4 ]
 [-0.3  -0.19  0.5   0.5 ]
 [-0.3  -0.    0.5   0.4 ]
 [ 0.2   0.51 -0.9   0.7 ]]
Updated Weights for Hidden Layer:
 [[ 0.52  0.81  0.21  0.41]
 [ 0.48  0.19  0.29 -0.51]]
Updated Biases for Input Layer:
 [ 0.  0. -0.  0.]
Updated Biases for Hidden Layer:
 [ 0.02 -0.02]


In [ ]:
(np.exp(-10)/(np.exp(-10)+1)**2)*2

9.079161547190333e-05

In [ ]:
np.outer(h2,h2)

array([[0.59341754, 0.17691845],
       [0.17691845, 0.05274556]])