In [ ]:
!pip install torch

In [2]:
import torch

In [3]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
my_torch = my_torch.reshape(2,5)
print(my_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [5]:
torch_2 = my_torch.reshape(2,-1)
print(torch_2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [6]:
my_torch2 = torch.arange(10)
print(my_torch2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
my_torch2 = my_torch2.view(2,5)
print(my_torch2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [8]:
my_torch2 = my_torch2.clone()
print(my_torch2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [9]:
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(5,-1)
print(my_torch3)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [10]:
print(my_torch3[:,1:]) # for retaining the structure

tensor([[1],
        [3],
        [5],
        [7],
        [9]])
